// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCNlGvyA03tKLCMQSX63a1TF8PxMaxRaOI',
    appId: '1:369296225542:web:fc6dc44cf953f960aeda87',
    messagingSenderId: '369296225542',
    projectId: 'cmsc23-todo-app-jfmanalang',
    authDomain: 'cmsc23-todo-app-jfmanalang.firebaseapp.com',
    storageBucket: 'cmsc23-todo-app-jfmanalang.appspot.com',
    measurementId: 'G-LD5RRYQ33M',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyClv0OjX_sY8BN_O7Def38KfXcgwpun_os',
    appId: '1:369296225542:android:18701be95f640ff7aeda87',
    messagingSenderId: '369296225542',
    projectId: 'cmsc23-todo-app-jfmanalang',
    storageBucket: 'cmsc23-todo-app-jfmanalang.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCQoPN9u1_GNoNtaVGXOijL-trHV1awV9M',
    appId: '1:369296225542:ios:9a192cd9a43c38a0aeda87',
    messagingSenderId: '369296225542',
    projectId: 'cmsc23-todo-app-jfmanalang',
    storageBucket: 'cmsc23-todo-app-jfmanalang.appspot.com',
    iosClientId: '369296225542-fg35uo6jvckviso5cqgbkdrprhoj4v10.apps.googleusercontent.com',
    iosBundleId: 'com.example.week7NetworkingDiscussion',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCQoPN9u1_GNoNtaVGXOijL-trHV1awV9M',
    appId: '1:369296225542:ios:9a192cd9a43c38a0aeda87',
    messagingSenderId: '369296225542',
    projectId: 'cmsc23-todo-app-jfmanalang',
    storageBucket: 'cmsc23-todo-app-jfmanalang.appspot.com',
    iosClientId: '369296225542-fg35uo6jvckviso5cqgbkdrprhoj4v10.apps.googleusercontent.com',
    iosBundleId: 'com.example.week7NetworkingDiscussion',
  );
}
